'use client';
import {useState,useEffect} from 'react';
import {LeadBoard} from './lead-board';
import {type ContentPage} from '@/lib/content';
type Entry={key:string;draft:ContentPage;published:ContentPage;updated:string};
type RequestEntry={id:string;payload:string;status:string;filename:string|null;created:number};
export function AdminEditor(){const [entries,setEntries]=useState<Entry[]>([]);const [key,setKey]=useState('tr:about');const [text,setText]=useState('');const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);const [reviewed,setReviewed]=useState(false);
 async function load(selected:string){try{const r=await fetch('/api/admin');const d=await r.json() as {error:string;entries:Entry[];requests:RequestEntry[]};if(!r.ok){setMessage(d.error);return}setEntries(d.entries);const entry=d.entries.find((e:Entry)=>e.key===selected);if(entry){setText(JSON.stringify(entry.draft,null,2));setReviewed(!!entry.draft.reviewed)}}catch{setMessage('Yönetim verileri yüklenemedi.')}}
 useEffect(()=>{let active=true;fetch('/api/admin').then(r=>r.json() as Promise<{entries?:Entry[];requests?:RequestEntry[];error?:string}>).then(d=>{if(!active)return;if(d.error){setMessage(d.error);return}setEntries(d.entries||[]);const first=d.entries?.find(e=>e.key==='tr:about');if(first){setText(JSON.stringify(first.draft,null,2));setReviewed(!!first.draft.reviewed)}}).catch(()=>{if(active)setMessage('Yönetim verileri yüklenemedi.')});return()=>{active=false}},[]);
 const entry=entries.find(e=>e.key===key);
 function select(value:string){setKey(value);const e=entries.find(x=>x.key===value);if(e){setText(JSON.stringify(e.draft,null,2));setReviewed(!!e.draft.reviewed);setMessage('')}}
 async function save(action:string){setSaving(true);try{const content=JSON.parse(text);content.reviewed=reviewed;const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key,action,content})});const d=await r.json() as {error:string;entries:Entry[];requests:RequestEntry[]};setMessage(r.ok?(action==='publish'?'İçerik bu uygulamada yayınlandı. Canlı dağıtım yapılmadı.':'Kaydedildi.'):d.error);if(r.ok)await load(key)}catch{setMessage('Geçerli JSON girin; alanların biçimini koruyun.')}finally{setSaving(false)}}
 return <><p>Her sayfanın dört dildeki içeriğini, SEO alanlarını, teknik tablolarını ve galeri sırasını buradan düzenleyebilirsiniz. Kaynak adresi ve dil eşlemeleri sabittir. Taslak kaydı ziyaretçiye sunulan sürümü değiştirmez.</p><div className="admin-toolbar"><label className="field">İçerik / Dil<select value={key} onChange={e=>select(e.target.value)}>{entries.map(e=><option value={e.key} key={e.key}>{e.draft.lang.toUpperCase()} — {e.draft.title}</option>)}</select></label>{entry&&<a href={entry.draft.path+'?preview=1'} target="_blank" className="text-link" rel="noopener noreferrer">Taslağı önizle ↗</a>}</div><label className="field">Düzenlenebilir içerik (JSON)<textarea className="json-editor" value={text} onChange={e=>setText(e.target.value)} spellCheck={false}/></label><label className="consent" style={{marginBlock:20}}><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>Teknik / hukuki içerik yetkili kişi tarafından incelendi ve yayın için onaylandı.</label><div className="admin-buttons"><button className="button outline" disabled={saving} onClick={()=>save('save')}>Taslağı kaydet</button><button className="button yellow" disabled={saving} onClick={()=>save('publish')}>İçeriği yayınla</button><button className="button outline" disabled={saving} onClick={()=>save('unpublish')}>Taslak durumuna al</button></div>{message&&<p role="status" className="draft-banner" style={{marginTop:20}}>{message}</p>}<LeadBoard/></>
}
