import {TechnicalBrief} from './technical-brief';
import {ArrowUpRight,Phone,Mail,MessageCircle} from 'lucide-react';
import {PageHeading,Picture,Prose,ContactAside,SectionHeading} from './site';
import {Gallery,ProjectGrid} from './site-interactions';
import {RequestForm,NeedsForm} from './request-form';
import {copy} from '@/lib/i18n';
import {getPage,contact,type ContentPage} from '@/lib/content';
import {JournalIndex,JournalArticle} from './journal';
import {designCopy} from '@/lib/design-copy';
import {legalBlocks} from '@/lib/legal';
export function ContentPageView({page,all,query,formsEnabled}:{page:ContentPage;all:ContentPage[];query:Record<string,string|undefined>;formsEnabled:boolean}){
 const lang=page.lang,t=copy[lang],get=(id:string)=>all.find(p=>p.id===id&&p.lang===lang)||getPage(id,lang);const projects=['stainless','coil','steel'].map(get);
 const currentService=['piping','thermal','melting'].find(id=>id===query.service||get(id).path.split('/').pop()===query.service)||'';
 const currentProject=['stainless','coil','steel'].includes(query.project||'')?query.project!:'';
 const service=page.kind==='service'?page.id:page.kind==='project'?'piping':page.kind==='solution'?'melting':'';
 const related=page.id==='thermal'?projects.filter(p=>p.id==='coil'):projects;
 if(page.id==='contact'){const d=designCopy(lang);return <><section className="contact-heading container"><span className="eyebrow">{t.contact} / MAB TEKNOLOJİ</span><h1>{d.contactTitle}</h1><p>{d.contactLead}</p></section><section className="contact-studio container"><div className="contact-studio-info"><Picture name="steel-enhanced" lang={lang}/><div className="contact-studio-copy"><span className="eyebrow">{t.direct}</span><h2>{d.startProject}</h2>{[{label:t.phone,value:contact.phone,url:'tel:'+contact.tel,Icon:Phone},{label:t.email,value:contact.email,url:'mailto:'+contact.email,Icon:Mail},{label:'WhatsApp',value:contact.phone,url:contact.whatsapp,Icon:MessageCircle}].map(x=><a href={x.url} key={x.label}><x.Icon size={20}/><span><small>{x.label}</small><bdi>{x.value}</bdi></span><ArrowUpRight size={20}/></a>)}</div></div><div className="contact-studio-form"><span className="eyebrow">{t.contact}</span><h2>{d.startProject}</h2><RequestForm lang={lang} kind="contact" enabled={formsEnabled}/></div></section>{page.blocks.length>0&&<section className="container contact-source"><Prose blocks={page.blocks}/><div className="contact-source-links"><a className="button dark" href={get('quote').path}>{t.quote}<ArrowUpRight size={18}/></a><a className="button outline" href={get('survey').path}>{t.survey}<ArrowUpRight size={18}/></a></div></section>}</>}
 if(page.id==='blog')return <JournalIndex page={page} all={all}/>;
 if(page.kind==='article')return <JournalArticle page={page} all={all}/>;
 return <><PageHeading page={page}/><section className="container page-body">
 {page.id==='about'&&<div className="detail-layout"><div><Picture name="1-44-kspMeuvS" lang={lang} className="about-portrait" priority/><dl className="meta-strip">{page.meta.map(m=><div key={m.key}><dt>{m.key}</dt><dd>{m.value}</dd></div>)}</dl><Prose blocks={page.blocks}/><div className="value-cards" style={{marginTop:35}}>{page.values.map(v=><article className="value-card" key={v.title}><h3>{v.title}</h3><p>{v.description}</p></article>)}</div></div><ContactAside lang={lang}/></div>}
 {page.id==='services'&&['piping','thermal'].map((id,i)=>{const p=get(id);return <article className="service-list-item" key={id}><div className="service-list-visual"><Picture name={i===0?'1-44-kspMeuvS':'1-11-6FCPOeYc'} lang={lang}/></div><div><span className="eyebrow">0{i+1} — {p.meta[0]?.value}</span><h2>{p.title}</h2><p>{p.description}</p><a className="text-link" href={p.path}>{t.details}<ArrowUpRight size={18}/></a></div></article>})}
 {page.id==='projects'&&<ProjectGrid lang={lang} items={projects} filters initialCategory={query.kategori?.includes('buhar')||query.kategori?.includes('steam')||query.kategori?.includes('parovye')?'__empty_source_category__':''}/>}
 {['service','project','solution'].includes(page.kind)&&<><div className="detail-layout"><div>{page.kind==='project'&&<><Picture name={page.images[0].key} lang={lang} className="detail-image" priority/><dl className="meta-strip">{page.meta.filter(m=>!/20/.test(m.value)).map(m=><div key={m.key}><dt>{m.key}</dt><dd>{m.value}</dd></div>)}<div><dt>{t.year}</dt><dd>{page.id==='stainless'?'2024':'2023'}</dd></div></dl></>}
 <Prose blocks={page.blocks}/>{page.kind==='service'&&<><h2 className="technical-heading">{t.technical}</h2><p className="muted" style={{marginTop:15}}>{t.technicalNote}</p>{page.tables.map((table,i)=><div className="table-wrap" key={i}><table><thead><tr>{table[0].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{table.slice(1).map((r,j)=><tr key={j}>{r.map((v,k)=><td key={k}>{v}</td>)}</tr>)}</tbody></table></div>)}<h2 className="technical-heading">{t.applications}</h2><p className="muted" style={{marginTop:18}}>{page.description}</p><h2 className="technical-heading">{t.process}</h2><ol className="process-list">{t.processSteps.split('|').map(s=><li key={s}>{s}</li>)}</ol></>}
 {page.kind==='solution'&&<><div className="table-wrap"><table><thead><tr><th scope="col">{t.parameter}</th><th scope="col">{t.value}</th></tr></thead><tbody>{page.options.map(o=><tr key={o.title}><td>{o.title}</td><td><p>{o.description}</p><ul>{o.items.map(x=><li key={x}>• {x}</li>)}</ul></td></tr>)}</tbody></table></div><NeedsForm lang={lang}/></>}
 {page.kind==='project'&&<><h2 className="technical-heading">{t.gallery}</h2><p className="muted" style={{marginTop:15}}>{t.photoNote}</p><Gallery page={page}/><div style={{marginTop:35}}><span className="eyebrow">{t.relatedService}</span><a className="text-link" href={get('piping').path}>{get('piping').title}<ArrowUpRight size={18}/></a></div></>}
 </div><ContactAside lang={lang} service={service} project={page.kind==='project'?page.id:''}/></div>{page.kind!=='solution'&&<div style={{marginTop:70}}><SectionHeading kicker={t.projects} title={t.relatedProjects}/><ProjectGrid items={related.filter(p=>p.id!==page.id)} lang={lang}/></div>}</>}
 {page.id==='solutions'&&<article className="service-list-item"><div className="service-list-visual"><Picture name="1-14-swPI4ROa" lang={lang}/></div><div><span className="eyebrow">{t.solutionKicker}</span><h2>{get('melting').title}</h2><p>{t.solutionLead}</p><a className="button yellow" href={get('melting').path}>{t.details}<ArrowUpRight size={18}/></a></div></article>}
 {['contact','quote','survey'].includes(page.id)&&<>{page.id==='contact'&&<div className="contact-methods">{[{title:t.phone,icon:Phone,label:contact.phone,url:'tel:'+contact.tel},{title:t.email,icon:Mail,label:contact.email,url:'mailto:'+contact.email},{title:'WhatsApp',icon:MessageCircle,label:t.contact,url:contact.whatsapp}].map(m=><article className="contact-method" key={m.title}><m.icon size={24} strokeWidth={1.4}/><h2>{m.title}</h2><a href={m.url}><bdi>{m.label}</bdi></a></article>)}</div>}<div className="detail-layout"><div><TechnicalBrief lang={lang} kind={page.id as 'quote'|'survey'} service={currentService} project={currentProject} needs={(query.needs||'').slice(0,4000)} enabled={formsEnabled}/>{page.blocks.length>0&&<div style={{marginTop:35}}><Prose blocks={page.blocks}/></div>}</div><ContactAside lang={lang}/></div></>}
 {['privacy','kvkk','cookies'].includes(page.id)&&<div style={{maxWidth:850}}>{page.status==='draft'&&<div className="draft-banner"><strong>{t.legalDraft}</strong></div>}<Prose blocks={page.blocks.length?page.blocks:legalBlocks(lang,page.id)}/><div className="article-sources"><h2>{t.sources}</h2><a href="https://www.kvkk.gov.tr/Icerik/2033/Aydinlatma-Yukumlulugu-" target="_blank" rel="noopener noreferrer">KVKK — {t.kvkk}</a><a href="https://www.kvkk.gov.tr/Icerik/7353/Cerez-Uygulamalari-Hakkinda-Rehber" target="_blank" rel="noopener noreferrer">KVKK — {t.cookies}</a></div></div>}
 {page.id==='sitemap'&&<div className="sitemap-list">{all.filter(p=>p.lang===lang&&p.id!=='sitemap').map(p=><a key={p.id} href={p.path}>{p.title}{p.status==='draft'?` · ${p.kind==='article'?t.draft:t.legalDraft}`:''}</a>)}</div>}
 </section></>
}
