'use client';
import {useEffect,useRef,useState,useSyncExternalStore} from 'react';
import {Sun,Moon,Phone,Mail,MessageCircle,X,Copy,Check,Printer} from 'lucide-react';
import {designCopy} from '@/lib/design-copy';
import {copy,type Lang} from '@/lib/i18n';
const subscribe=(fn:()=>void)=>{window.addEventListener('mab-theme-change',fn);window.addEventListener('storage',fn);return()=>{window.removeEventListener('mab-theme-change',fn);window.removeEventListener('storage',fn)}};
export function ThemeToggle({lang}:{lang:Lang}){const t=designCopy(lang);const dark=useSyncExternalStore(subscribe,()=>document.documentElement.dataset.theme==='dark',()=>false);return <button className="header-icon theme-toggle" aria-label={dark?t.light:t.dark} title={dark?t.light:t.dark} onClick={()=>{const next=dark?'light':'dark';document.documentElement.dataset.theme=next;try{localStorage.setItem('mab-theme-v3',next)}catch{}window.dispatchEvent(new Event('mab-theme-change'))}}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button>}
export function Experience({lang}:{lang:Lang}){const t=designCopy(lang);
 useEffect(()=>{let navigateTimer:ReturnType<typeof setTimeout>,escapeTimer:ReturnType<typeof setTimeout>;const clear=()=>{delete document.documentElement.dataset.navigating;clearTimeout(navigateTimer);clearTimeout(escapeTimer)};const click=(e:MouseEvent)=>{if(e.defaultPrevented||e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;const a=(e.target as HTMLElement)?.closest('a');if(!a||a.hasAttribute('download')||(a.target&&a.target!=='_self'))return;const url=new URL(a.href,location.href);if(url.origin!==location.origin||url.protocol!==location.protocol||(url.pathname===location.pathname&&url.search===location.search))return;e.preventDefault();document.documentElement.dataset.navigating='true';clearTimeout(navigateTimer);navigateTimer=setTimeout(()=>location.assign(url.href),matchMedia('(prefers-reduced-motion: reduce)').matches?0:220);escapeTimer=setTimeout(clear,10000)};document.addEventListener('click',click);window.addEventListener('pageshow',clear);return()=>{clear();document.removeEventListener('click',click);window.removeEventListener('pageshow',clear)}},[]);
 useEffect(()=>{const reduce=matchMedia('(prefers-reduced-motion: reduce)');let frame=0;const scroll=()=>{if(frame)return;frame=requestAnimationFrame(()=>{frame=0;document.documentElement.dataset.scrolled=String(scrollY>30);document.documentElement.dataset.scrollEnd=String(scrollY+innerHeight>=document.documentElement.scrollHeight-12);const hero=document.querySelector('.hero-intro');if(hero&&!reduce.matches){const r=hero.getBoundingClientRect();const v=Math.min(1,Math.max(0,-r.top/Math.max(1,r.height)));(hero as HTMLElement).style.setProperty('--scroll-blur',`${(v*5).toFixed(2)}px`);(hero as HTMLElement).style.setProperty('--scroll-fade',String(1-v*.3))}})};const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){e.target.classList.add('revealed');observer.unobserve(e.target)}},{threshold:.08});document.querySelectorAll('.expertise-card,.industry-idea,.journal-card,.contact-studio-info,.method-grid article,.section-heading').forEach((el,i)=>{(el as HTMLElement).style.setProperty('--reveal-delay',`${(i%3)*75}ms`);observer.observe(el)});window.addEventListener('scroll',scroll,{passive:true});scroll();return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',scroll);observer.disconnect()}},[]);
 return <><div className="scroll-edge-blur" aria-hidden="true"/><div className="page-loader" role="status" aria-live="polite"><div className="loader-emblem"><img src="/media/brand/mark.webp" alt="" width={72} height={72}/><span/></div><strong>MAB <span>TEKNOLOJİ</span></strong><p>{t.loading}</p><div className="loader-line"><span/></div><small>{t.introLine}</small></div></>
}
export function QuickContact({lang}:{lang:Lang}){const [open,setOpen]=useState(false);const t=designCopy(lang);const c=copy[lang];return <div className="contact-dock" onKeyDown={e=>{if(e.key==='Escape')setOpen(false)}}>{open&&<div id="quick-contact-panel" className="contact-dock-panel"><strong>{t.startProject}</strong><a href="tel:+905444534163"><Phone size={17}/>{c.call}</a><a href="mailto:info@mabteknoloji.com.tr"><Mail size={17}/>{c.write}</a><a href="https://wa.me/905444534163" target="_blank" rel="noopener noreferrer"><MessageCircle size={17}/>WhatsApp</a></div>}<button className="contact-dock-trigger" aria-label={open?c.close:t.quickContact} aria-expanded={open} aria-controls="quick-contact-panel" onClick={()=>setOpen(!open)}>{open?<X size={22}/>:<MessageCircle size={22}/>}</button></div>}
export function ArticleTools({lang}:{lang:Lang}){const [state,setState]=useState('');const t=designCopy(lang);return <div className="article-tools"><button onClick={async()=>{try{await navigator.clipboard.writeText(location.href);setState(t.copied)}catch{setState(t.copyError)}}}>{state===t.copied?<Check size={16}/>:<Copy size={16}/>}<span>{t.copyLink}</span></button><button onClick={()=>window.print()}><Printer size={16}/><span>{t.print}</span></button><span className="sr-only" role="status">{state}</span></div>}
export function ReadingProgress({lang}:{lang:Lang}){const bar=useRef<HTMLDivElement>(null);useEffect(()=>{let frame=0;const update=()=>{if(frame)return;frame=requestAnimationFrame(()=>{frame=0;const article=document.querySelector('.article-prose');if(!article||!bar.current)return;const rect=article.getBoundingClientRect();const progress=Math.min(1,Math.max(0,(innerHeight*.3-rect.top)/Math.max(1,rect.height-innerHeight*.5)));bar.current.style.transform=`scaleX(${progress})`;bar.current.parentElement?.setAttribute('aria-valuenow',String(Math.round(progress*100)))})};window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);update();return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',update);window.removeEventListener('resize',update)}},[]);return <div className="reading-progress" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={0} aria-label={designCopy(lang).reading}><div ref={bar}/></div>}
