import {ArrowUpRight,Clock3,ArrowLeft} from 'lucide-react';
import {copy} from '@/lib/i18n';
import {designCopy} from '@/lib/design-copy';
import {media,href,type ContentPage} from '@/lib/content';
import {JournalBrowser,JournalCard,type ArticleSummary} from './journal-browser';
import {ArticleTools,ReadingProgress} from './experience';
export function summarize(p:ContentPage,all:ContentPage[]):ArticleSummary{const topic=all.find(x=>x.id===p.related&&x.lang===p.lang);const im=media[p.images[0]?.key||p.id];return{id:p.id,title:p.title,description:p.description,path:p.path,category:p.related||'piping',topic:topic?.title||copy[p.lang].blog,minutes:Math.max(2,Math.ceil(p.blocks.map(b=>b.text||'').join(' ').split(/\s+/).length/180)),image:im.src,srcSet:im.srcSet}}
export function JournalIndex({page,all}:{page:ContentPage;all:ContentPage[]}){const lang=page.lang,c=copy[lang],t=designCopy(lang);const articles=all.filter(p=>p.kind==='article'&&p.lang===lang);const items=articles.map(p=>summarize(p,all)),featured=items[0];return <><section className="journal-heading container"><span className="eyebrow">MAB JOURNAL</span><h1>{t.journalTitle}</h1><p>{page.description}</p><span className="edition-label">01 — {c.blog}</span></section>{featured&&<section className="journal-feature container"><a className="journal-feature-image" href={featured.path}><img src={featured.image} srcSet={featured.srcSet} sizes="(max-width: 800px) 94vw, 60vw" width={1600} height={900} alt={featured.title} fetchPriority="high"/></a><div className="journal-feature-copy"><span className="eyebrow">{t.featured}</span><div className="journal-meta"><span>{featured.topic}</span><span><Clock3 size={14}/>{featured.minutes} {t.minutes}</span></div><h2><a href={featured.path}>{featured.title}</a></h2><p>{featured.description}</p><a className="button dark" href={featured.path}>{c.read}<ArrowUpRight size={18}/></a></div></section>}<section className="container journal-all"><div className="journal-section-heading"><h2>{t.latest}</h2><span>0{items.length}</span></div><JournalBrowser items={items} lang={lang}/></section></>}
export function JournalArticle({page,all}:{page:ContentPage;all:ContentPage[]}){const lang=page.lang,c=copy[lang],t=designCopy(lang),item=summarize(page,all);const related=all.filter(p=>p.kind==='article'&&p.lang===lang&&p.id!==page.id).sort((a,b)=>Number(b.related===page.related)-Number(a.related===page.related)).slice(0,3);return <><ReadingProgress lang={lang}/><header className="article-heading container"><a className="article-back" href={href('blog',lang)}><ArrowLeft size={16}/>{c.blog}</a><div className="journal-meta"><span>{item.topic}</span><span><Clock3 size={14}/>{item.minutes} {t.minutes}</span></div><h1>{page.title}</h1><p>{page.description}</p><ArticleTools lang={lang}/></header><figure className="article-cover container"><img src={item.image} srcSet={item.srcSet} sizes="(max-width: 800px) 94vw, 85vw" width={1600} height={900} alt={page.title} fetchPriority="high"/></figure><section className="container article-layout journal-article-layout"><aside className="article-sidebar"><nav className="toc" aria-label={c.toc}><strong>{c.toc}</strong>{page.blocks.map((b,i)=>b.type==='h2'?<a href={`#section-${i}`} key={i}><span>{String(page.blocks.slice(0,i+1).filter(x=>x.type==='h2').length).padStart(2,'0')}</span>{b.text}</a>:null)}</nav><a className="article-consult" href={href('quote',lang)+'?service='+page.related}><span>{t.startProject}</span><ArrowUpRight size={22}/></a></aside><article className="article-prose"><div className="article-summary"><span className="eyebrow">{c.scope}</span><p>{page.description}</p></div>{page.status==='draft'&&<div className="draft-banner">{c.draft}</div>}<div className="prose">{page.blocks.map((b,i)=>b.type==='h2'?<h2 key={i} id={`section-${i}`}>{b.text}</h2>:b.type==='h3'?<h3 key={i}>{b.text}</h3>:b.type==='list'?<ul key={i}>{b.items?.map(x=><li key={x}>{x}</li>)}</ul>:<p key={i}>{b.text}</p>)}</div><div className="article-sources"><h2>{c.sources}</h2>{page.sources?.map((s,i)=><a href={s.url} key={s.url} target="_blank" rel="noopener noreferrer"><span>0{i+1}</span>{s.title}<ArrowUpRight size={17}/></a>)}</div><div className="article-service-link"><span className="eyebrow">{c.relatedService}</span><a href={href(page.related||'piping',lang)}>{item.topic}<ArrowUpRight size={22}/></a></div></article></section><section className="container article-related"><h2>{t.relatedReading}</h2><div className="journal-grid">{related.map(p=><JournalCard item={summarize(p,all)} lang={lang} key={p.id}/>)}</div></section></>}
