'use client';
import {useEffect,useState} from 'react';
const stages={new:'Yeni talep',review:'İnceleniyor',survey:'Keşif planlanıyor',quoted:'Teklif iletildi',won:'İşe dönüştü',lost:'Kapandı'};
type Lead={id:string;payload:string;status:string;filename:string|null;created:number;stage:keyof typeof stages;owner:string;note:string;nextContact:string;version:number};
type Event={entityId:string;action:string;actor:string;created:number};
type Data={leads:Lead[];events:Event[];notificationsConfigured:boolean};
function LeadCard({lead,events,configured,reload}:{lead:Lead;events:Event[];configured:boolean;reload:()=>Promise<void>}){const [draft,setDraft]=useState({stage:lead.stage,owner:lead.owner,note:lead.note,nextContact:lead.nextContact});const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);const p=JSON.parse(lead.payload) as Record<string,string>;const overdue=lead.nextContact&&lead.nextContact<new Date().toLocaleDateString('en-CA')&&!['won','lost'].includes(lead.stage);
 async function action(retry=false){setSaving(true);setMessage('');try{const response=await fetch('/api/admin/leads',{method:retry?'POST':'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(retry?{id:lead.id,action:'retry-notification'}:{id:lead.id,version:lead.version,...draft})});const data=await response.json() as {error?:string};setMessage(response.ok?retry?'Bildirim iletildi.':'Takip kaydedildi.':data.error||'İşlem başarısız.');if(response.ok)await reload()}catch{setMessage('Bağlantı kurulamadı. Değişiklikleriniz bu ekranda duruyor.')}finally{setSaving(false)}}
 return <details className="lead-card"><summary><span><strong>{p.name}</strong><small>{p.company||p.email} · {new Date(lead.created).toLocaleDateString('tr-TR')}</small></span><span><span className="lead-badge">{stages[lead.stage]}</span>{lead.nextContact&&<small className={overdue?'lead-overdue':''}>{overdue?'Görüşme tarihi geçti: ':'Görüşme: '}{lead.nextContact}</small>}</span></summary><div className="lead-details"><p className="lead-receipt">Referans: {lead.id}</p><dl>{Object.entries({Tür:p.kind,Dil:p.lang,'E-posta':p.email,Telefon:p.phone,Firma:p.company,Görev:p.role,Konum:p.location,'Tercih edilen tarih':p.date,Kanal:p.channel,Hizmet:p.service,Proje:p.project}).filter(([,value])=>value).map(([key,value])=><div key={key} style={{display:'contents'}}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><h3>Talep detayları</h3><p>{p.message}</p>{p.needs&&<><h3>Teknik ön bilgiler</h3><p>{p.needs}</p></>}{lead.filename&&<p><a className="text-link" href={'/api/admin/attachment/'+lead.id}>{lead.filename} ↗</a></p>}<div className="form-grid"><label className="field">Takip aşaması<select value={draft.stage} onChange={e=>setDraft({...draft,stage:e.target.value as Lead['stage']})}>{Object.entries(stages).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="field">Sorumlu kişi<input maxLength={100} value={draft.owner} onChange={e=>setDraft({...draft,owner:e.target.value})}/></label><label className="field">Sonraki görüşme tarihi<input type="date" value={draft.nextContact} onChange={e=>setDraft({...draft,nextContact:e.target.value})}/></label><label className="field span-2">İç takip notu<textarea maxLength={2000} value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></div><div className="admin-buttons"><button className="button dark" type="button" disabled={saving} onClick={()=>action()}>Takibi kaydet</button>{configured&&['received','failed','notifying'].includes(lead.status)&&<button className="button outline" type="button" disabled={saving} onClick={()=>action(true)}>E-posta bildirimini yeniden dene</button>}</div>{message&&<p role="status">{message}</p>}<p className="lead-receipt">E-posta bildirimi: {lead.status==='delivered'?'Sağlayıcı kabul etti':lead.status==='notifying'?'İşleniyor':lead.status==='failed'?'Yeniden deneme bekliyor':'Bekliyor'}</p>{events.length>0&&<details><summary>İşlem geçmişi</summary><ul className="lead-audit">{events.map((e,i)=><li key={i}>{new Date(e.created).toLocaleString('tr-TR')} · {e.action} · {e.actor}</li>)}</ul></details>}</div></details>
}
export function LeadBoard(){const [data,setData]=useState<Data|null>(null);const [error,setError]=useState('');const [filter,setFilter]=useState('all');const [search,setSearch]=useState('');async function reload(){try{const r=await fetch('/api/admin/leads');const d=await r.json() as Data&{error:string};if(!r.ok)throw Error(d.error);setData(d);setError('')}catch(e){setError(e instanceof Error?e.message:'Talepler yüklenemedi.')}}useEffect(()=>{let active=true;fetch('/api/admin/leads').then(async r=>{const d=await r.json() as Data&{error:string};if(!r.ok)throw Error(d.error);if(active)setData(d)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[]);const leads=data?.leads.filter(l=>(filter==='all'||l.stage===filter)&&(l.payload+' '+l.owner).toLocaleLowerCase('tr').includes(search.toLocaleLowerCase('tr')))||[];
 return <section className="lead-board"><div className="lead-board-head"><div><span className="eyebrow">MAB / TALEP TAKİBİ</span><h2>Görüşmeden projeye.</h2><p>Son 100 talep. Tarihler takip içindir; otomatik hatırlatma gönderilmez.</p></div><button type="button" className="button outline" onClick={reload}>Güncel kayıtları yükle</button></div>{error&&<p role="alert">{error}</p>}{data&&!data.notificationsConfigured&&<p className="form-note">Talepler yönetim paneline kaydedilir. E-posta bildirimi için gönderici bağlantısı yapılandırılmalıdır.</p>}<label className="field">Ad, firma veya sorumlu ara<input type="search" value={search} onChange={e=>setSearch(e.target.value)} maxLength={200}/></label><div className="lead-filters">{Object.entries({all:'Tümü',...stages}).map(([key,label])=><button type="button" key={key} aria-pressed={filter===key} onClick={()=>setFilter(key)}>{label} ({data?.leads.filter(l=>key==='all'||l.stage===key).length||0})</button>)}</div>{!data&&!error&&<p role="status">Talepler yükleniyor…</p>}{data&&!leads.length&&<p>Bu görünümde talep bulunmuyor.</p>}{leads.map(lead=><LeadCard key={lead.id+':'+lead.version+':'+lead.status} lead={lead} events={data!.events.filter(e=>e.entityId===lead.id)} configured={data!.notificationsConfigured} reload={reload}/>)}</section>
}
