'use client';
import {useEffect,useRef,useState} from 'react';
import {Search,ArrowUpRight,ChevronDown,ArrowRight,Factory,Flame,Box,BookOpen,ClipboardList,X} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from './ui/dialog';
import {copy,type Lang} from '@/lib/i18n';
import {designCopy} from '@/lib/design-copy';
import {href,getPage} from '@/lib/client-content';
import routes from '@/content/routes.json';
export function MegaNav({lang,id}:{lang:Lang;id:string}){const [open,setOpen]=useState('');const ref=useRef<HTMLElement>(null);const c=copy[lang],t=designCopy(lang);
 useEffect(()=>{const close=(e:PointerEvent)=>{if(!ref.current?.contains(e.target as Node))setOpen('')};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close)},[]);
 const groups={expertise:[{id:'piping',icon:Factory},{id:'thermal',icon:Flame},{id:'melting',icon:Box}],knowledge:[{id:'blog',icon:BookOpen},{id:'survey',icon:ClipboardList},{id:'about',icon:Factory}]};
 return <nav ref={ref} className="mega-nav" aria-label={c.menu} onKeyDown={e=>{if(e.key==='Escape'){setOpen('');(e.target as HTMLElement).closest('.mega-item')?.querySelector('button')?.focus()}}} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setOpen('')}}><a href={href('about',lang)} aria-current={id==='about'?'page':undefined}>{c.about}</a>{(['expertise','knowledge'] as const).map((key,i)=><div className="mega-item" key={key}>{i===1&&<a className="projects-nav" href={href('projects',lang)} aria-current={id==='projects'?'page':undefined}>{c.projects}</a>}<button className="mega-trigger" aria-expanded={open===key} aria-controls={`mega-${key}`} onClick={()=>setOpen(open===key?'':key)}>{t[key]}<ChevronDown size={13}/></button>{open===key&&<div className="mega-panel" id={`mega-${key}`}><div className="mega-intro"><span className="eyebrow">MAB TEKNOLOJİ</span><h2>{key==='expertise'?c.serviceTitle:t.journalTitle}</h2><a className="text-link" href={href(key==='expertise'?'services':'blog',lang)}>{t.discover}<ArrowRight size={16}/></a></div><div className="mega-links">{groups[key].map(item=><a key={item.id} href={href(item.id,lang)}><item.icon size={22} strokeWidth={1.4}/><span>{item.id in c?c[item.id as keyof typeof c]:getPage(item.id,lang).title}</span><ArrowUpRight size={17}/></a>)}</div><a className="mega-feature" href={href(key==='expertise'?'stainless':'planning',lang)}><img src={key==='expertise'?'/media/1-44-kspMeuvS-480.webp':'/media/editorial/planning-768.webp'} alt="" width={480} height={300}/><span>{key==='expertise'?t.fieldNotes:t.featured}<ArrowUpRight size={17}/></span></a></div>}</div>)}<a href={href('contact',lang)}>{c.contact}</a></nav>}
export function SiteSearch({lang}:{lang:Lang}){const [open,setOpen]=useState(false),[query,setQuery]=useState('');const t=designCopy(lang),c=copy[lang];const entries=routes.filter(r=>r.lang===lang&&!['privacy','cookies','kvkk','sitemap'].includes(r.id)).map(r=>({...r,title:r.id in c?c[r.id as keyof typeof c]:r.title}));const normalize=(s:string)=>s.toLocaleLowerCase(lang).normalize('NFKD').replace(/[\u0300-\u036f]/g,'');const hits=entries.filter(r=>normalize(r.title).includes(normalize(query))).slice(0,8);
 return <><button className="header-icon search-trigger" aria-label={t.search} onClick={()=>setOpen(true)}><Search size={18}/></button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="search-dialog" showCloseButton={false}><DialogTitle>{t.search}</DialogTitle><DialogDescription className="sr-only">{t.searchHint}</DialogDescription><DialogClose className="search-close header-icon" aria-label={c.close}><X size={20}/></DialogClose><label className="search-field"><Search size={21}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.searchHint} aria-label={t.searchHint}/></label><div className="search-results">{hits.length?hits.map(r=><a href={r.path} key={r.path}><span>{r.title}</span><ArrowUpRight size={19}/></a>):<p role="status">{t.searchEmpty}</p>}</div></DialogContent></Dialog></>}
