'use client';
import {useState,useEffect,useRef} from 'react';
import {ArrowUpRight} from 'lucide-react';
import {designCopy} from '@/lib/design-copy';
import {copy,type Lang} from '@/lib/i18n';
import {href,getPage} from '@/lib/client-content';
function newId(){if(crypto.randomUUID)return crypto.randomUUID();const b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const h=Array.from(b,v=>v.toString(16).padStart(2,'0')).join('');return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`}
type FormProps={lang:Lang;kind:'contact'|'quote'|'survey';service?:string;project?:string;needs?:string;enabled:boolean;showContext?:boolean};
export function RequestForm({lang,kind,service='',project='',needs='',enabled,showContext=true}:FormProps){const t=copy[lang],d=designCopy(lang);const [status,setStatus]=useState('');const [sending,setSending]=useState(false);const [reference,setReference]=useState('');const token=useRef('');const requestId=useRef('');const statusRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{requestId.current=newId();if(enabled)fetch('/api/request-token').then(r=>r.json() as Promise<{token?:string}>).then(data=>{token.current=data.token||''}).catch(()=>{});},[enabled]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!enabled){const data=new FormData(e.currentTarget);const fields=['name','company','email','phone','role','location','date','service','message'];const body=fields.filter(k=>data.get(k)).map(k=>`${t[k as keyof typeof t]||k}: ${k==='service'?getPage(String(data.get(k)),lang)?.title||data.get(k):data.get(k)}`).join('\n')+(project?'\n'+t.projects+': '+getPage(project,lang).title:'')+(needs?'\n'+needs:'');window.location.href='mailto:info@mabteknoloji.com.tr?subject='+encodeURIComponent('MAB Teknoloji — '+t[kind])+'&body='+encodeURIComponent(body);setStatus('mailReady');return}const form=e.currentTarget;setSending(true);setStatus('');const fd=new FormData(form);fd.set('lang',lang);fd.set('kind',kind);fd.set('token',token.current);fd.set('requestId',requestId.current);fd.set('project',project);fd.set('needs',needs);for(const key of ['phone','company','role','location','date','channel','service'])if(!fd.has(key))fd.set(key,'');try{const r=await fetch('/api/requests',{method:'POST',body:fd});const data=await r.json() as {id:string;error:string};if(r.ok){setStatus('success');setReference(data.id);form.reset();requestId.current=newId();const fresh=await fetch('/api/request-token').then(r=>r.json() as Promise<{token?:string}>);token.current=fresh.token||''}else{if(data.error==='conflict')requestId.current=newId();setStatus(data.error==='unconfigured'?'error':data.error in t?data.error:'error')}}catch{setStatus('error')}finally{setSending(false);requestAnimationFrame(()=>statusRef.current?.focus())}}
 return <form className="request-form" onSubmit={submit}><p className="form-note">{t.required}</p>{project&&<div className="request-summary">{t.requestContext}: <strong>{getPage(project,lang)?.title}</strong></div>}{showContext&&needs&&<div className="request-summary"><strong>{t.needsSummary}</strong><p style={{whiteSpace:'pre-line',fontSize:14,margin:'10px 0 0'}}>{needs}</p></div>}<div className="form-grid" style={{marginTop:25}}>
 <label className="field">{t.name} *<input name="name" autoComplete="name" required minLength={2} maxLength={120}/></label><label className="field">{t.company}<input name="company" autoComplete="organization" maxLength={200}/></label>
 <label className="field">{t.email} *<input name="email" type="email" dir="ltr" autoComplete="email" required maxLength={254}/></label><label className="field">{t.phone}{kind!=='contact'?' *':''}<input name="phone" type="tel" dir="ltr" autoComplete="tel" required={kind!=='contact'} maxLength={50}/></label>
 {kind!=='contact'&&<><label className="field">{t.role}<input name="role" autoComplete="organization-title" maxLength={120}/></label><label className="field">{t.location}<input name="location" maxLength={250}/></label><label className="field span-2">{t.service}<select name="service" key={service} defaultValue={service}><option value="">—</option>{['piping','thermal','melting'].map(id=><option key={id} value={id}>{getPage(id,lang).title}</option>)}</select></label><label className="field">{t.channel}<select name="channel"><option value="">{t.any}</option><option value="phone">{t.phone}</option><option value="email">{t.email}</option><option value="whatsapp">WhatsApp</option></select></label>{kind==='survey'&&<label className="field">{t.date}<input type="date" name="date"/></label>}</>}
 <label className="field span-2">{t.message} *<textarea name="message" required minLength={15} maxLength={10000}/></label>
 {enabled&&kind!=='contact'&&<label className="field span-2">{t.file}<input name="file" type="file" accept=".pdf,.png,.jpg,.jpeg,.webp" onChange={e=>{if((e.target.files?.[0]?.size||0)>10*1024*1024){e.target.setCustomValidity(t.invalidFile);e.target.reportValidity()}else e.target.setCustomValidity('')}}/><span className="form-note">{t.fileHint}</span></label>}
 <label className="honeypot" aria-hidden>Website<input name="website" autoComplete="off" tabIndex={-1}/></label>
 <label className="consent span-2"><input type="checkbox" name="consent" required/><span><a href={href('kvkk',lang)} target="_blank" rel="noopener noreferrer">{t.consent}</a> *</span></label>
 {status&&<div className={`form-status span-2 ${status==='success'?'success':''}`} ref={statusRef} tabIndex={-1} role={status==='success'||status==='mailReady'?'status':'alert'}>{status==='mailReady'?d.mailReady:t[status as keyof typeof t]||t.error} {reference&&status==='success'?reference:''}</div>}
 <div className="span-2">{!enabled&&<p className="form-note mail-compose-note">{d.mailHint}</p>}<button className="button yellow" type="submit" disabled={sending}>{sending?t.sending:enabled?t.send:d.mailDraft}<ArrowUpRight size={18}/></button></div></div></form>
}
export function NeedsForm({lang}:{lang:Lang}){const t=copy[lang];function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);const summary=['material','capacity','energy','structure','control'].map(k=>`${t[k as keyof typeof t]}: ${data.get(k)||'—'}`).join('\n');document.documentElement.dataset.navigating='true';setTimeout(()=>location.assign(href('quote',lang)+'?service=melting&needs='+encodeURIComponent(summary)),matchMedia('(prefers-reduced-motion: reduce)').matches?0:220)}return <section className="needs-box" id="needs"><h2>{t.needsTitle}</h2><p>{t.needsNote}</p><form onSubmit={submit}><div className="form-grid"><label className="field">{t.material} *<input name="material" required maxLength={250}/></label><label className="field">{t.capacity}<input name="capacity" maxLength={250}/></label>{(['energy','structure','control'] as const).map(key=><label className="field" key={key}>{t[key]}<select name={key} defaultValue={t[`${key}Options`].split('|').at(-1)}>{t[`${key}Options`].split('|').map(x=><option key={x}>{x}</option>)}</select></label>)}</div><button type="submit" className="button yellow">{t.continue}<ArrowUpRight size={17}/></button></form></section>}
