'use client';
import { useState,useEffect,useRef } from 'react';
import { ArrowUpRight,ArrowLeft,ArrowRight,Globe,Menu,X,Plus,Check,ChevronDown } from 'lucide-react';
import { Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose } from '@/components/ui/dialog';
import { Accordion,AccordionItem,AccordionTrigger,AccordionContent } from '@/components/ui/accordion';
import {designCopy} from '@/lib/design-copy';
import { copy,languageNames,languages,type Lang } from '@/lib/i18n';
import { href,media,imageAlt,projectYear,projectCategory,type ContentPage } from '@/lib/client-content';
export function LanguagePicker({lang,id}:{lang:Lang;id:string}){
 const t=copy[lang]; const [open,setOpen]=useState(false);const [search,setSearch]=useState('');const root=useRef<HTMLDivElement>(null);
 useEffect(()=>{const onClick=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false)};document.addEventListener('pointerdown',onClick);return()=>document.removeEventListener('pointerdown',onClick)},[]);
 return <div className="language-picker" ref={root} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);root.current?.querySelector('button')?.focus()}}}><button className="language-trigger" aria-label={`${languageNames[lang]} (${lang.toUpperCase()}) — ${t.language}`} aria-expanded={open} aria-controls="language-options" onClick={()=>{setSearch(window.location.search);setOpen(!open)}}><Globe size={16}/><span className="language-current-name">{languageNames[lang]}</span><span className="language-current-code">{lang.toUpperCase()}</span><ChevronDown size={13}/></button>{open&&<div className="language-options" id="language-options"><p>{designCopy(lang).chooseLanguage}</p>{languages.map(l=><a key={l} href={href(id,l)+search} lang={l} hrefLang={l} aria-current={lang===l?'page':undefined}><span className="language-option-name">{languageNames[l]}<small>{l.toUpperCase()}</small></span>{lang===l?<Check size={17}/>:<ArrowUpRight size={17}/>}</a>)}</div>}</div>
}
export function MobileMenu({lang,id}:{lang:Lang;id:string}){
 const [open,setOpen]=useState(false);const t=copy[lang];
 return <><button className="mobile-menu-trigger icon-button" aria-label={t.menu} onClick={()=>setOpen(true)}><Menu/></button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="mobile-drawer" showCloseButton={false}><DialogTitle>{t.menu}</DialogTitle><DialogDescription className="sr-only">MAB Teknoloji</DialogDescription><DialogClose className="drawer-close icon-button" aria-label={t.close}><X/></DialogClose><nav className="mobile-nav">{['home','about','services','projects','solutions','blog','contact','quote','survey'].map(key=><a key={key} href={href(key,lang)} aria-current={id===key?'page':undefined}>{t[key as keyof typeof t]}<ArrowUpRight size={18}/></a>)}</nav></DialogContent></Dialog></>
}
export function ServiceAccordion({lang,items}:{lang:Lang;items:ContentPage[]}){
 const t=copy[lang];return <Accordion type="single" collapsible defaultValue="piping" className="service-accordion">{items.map((p,i)=>{const id=p.id;return <AccordionItem value={id} key={id}><AccordionTrigger><span className="service-title"><span className="service-no">0{i+1}</span>{p.title}</span></AccordionTrigger><AccordionContent><p>{p.description}</p><a className="text-link" href={p.path}>{t.details}<ArrowUpRight size={18}/></a></AccordionContent></AccordionItem>})}</Accordion>
}
export function FAQ({lang}:{lang:Lang}){const t=copy[lang];return <Accordion type="single" collapsible defaultValue="0" className="faq-accordion">{t.questions.split('|').map((q,i)=><AccordionItem value={String(i)} key={q}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent>{t.answers.split('|')[i]}</AccordionContent></AccordionItem>)}</Accordion>}
export function Gallery({page}:{page:ContentPage}){
 const t=copy[page.lang];const [index,setIndex]=useState<number|null>(null);const current=index===null?null:page.images[index];
 const move=(offset:number)=>setIndex(i=>i===null?null:(i+offset+page.images.length)%page.images.length);
 return <><div className="gallery-grid">{page.images.map((im,i)=><button className="gallery-item" key={im.key} onClick={()=>setIndex(i)} aria-label={`${t.enlarge}: ${(im.alt||imageAlt(im.key,page.lang))}`}><img src={media[im.key].src} srcSet={media[im.key].srcSet} sizes="(max-width: 768px) 90vw, 28vw" alt={(im.alt||imageAlt(im.key,page.lang))} width={media[im.key].width} height={media[im.key].height} loading="lazy"/><span><Plus size={20}/></span></button>)}</div><Dialog open={index!==null} onOpenChange={open=>{if(!open)setIndex(null)}}><DialogContent className="gallery-dialog" showCloseButton={false} onKeyDown={e=>{if(e.key==='ArrowRight')move(1);if(e.key==='ArrowLeft')move(-1)}}><DialogTitle>{page.title}</DialogTitle><DialogDescription>{t.photoNote}</DialogDescription><DialogClose aria-label={t.close} className="gallery-close icon-button"><X/></DialogClose>{current&&<img src={media[current.key].src} width={media[current.key].width} height={media[current.key].height} alt={(current.alt||imageAlt(current.key,page.lang))}/>}<div className="gallery-controls"><button className="icon-button" onClick={()=>move(-1)} aria-label={t.previous}><ArrowLeft/></button><span>{(index??0)+1} / {page.images.length}</span><button className="icon-button" onClick={()=>move(1)} aria-label={t.next}><ArrowRight/></button></div></DialogContent></Dialog></>
}
export function ProjectGrid({items,lang,filters=false,initialCategory=''}:{items:ContentPage[];lang:Lang;filters?:boolean;initialCategory?:string}){
 const t=copy[lang];const [year,setYear]=useState('');const [category,setCategory]=useState(initialCategory);
 const categories=Array.from(new Set(items.map(projectCategory))); const shown=items.filter(p=>(!year||projectYear(p)===year)&&(!category||projectCategory(p)===category));
 return <>{filters&&<div className="project-filters"><div className="filter-buttons" role="group" aria-label={t.year}>{['','2024','2023'].map(y=><button key={y} aria-pressed={year===y} onClick={()=>setYear(y)}>{y||t.all}</button>)}</div><label>{t.category}<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">{t.all}</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><span role="status">{shown.length} {t.results}</span></div>}<div className="project-grid">{shown.map(p=>{const im=p.images[0];return <article className="project-card" key={p.id}><a href={p.path} className="project-image" aria-label={`${projectYear(p)} · ${p.title}`}><img src={media[im.key].src} srcSet={media[im.key].srcSet} sizes="(max-width: 650px) 90vw, 30vw" alt={im.alt||imageAlt(im.key,lang)} width={media[im.key].width} height={media[im.key].height} loading="lazy"/><span className="project-year">{projectYear(p)}</span><span className="project-arrow"><ArrowUpRight size={20}/></span></a><p className="eyebrow project-category">{projectCategory(p)}</p><h3><a href={p.path}>{p.title}</a></h3>{filters&&<p>{p.description}</p>}</article>})}</div>{!shown.length&&<div className="empty-state"><p>{t.noProjects}</p><button className="button" onClick={()=>{setYear('');setCategory('')}}>{t.reset}</button></div>}</>
}
