import {leadCopy} from '@/lib/lead-copy';
import { ArrowUpRight,ArrowRight,FlaskConical,Factory,Wheat,Zap,Container,ShieldCheck,Ruler,Layers,Settings2,Phone,Mail } from 'lucide-react';
import { copy,type Lang } from '@/lib/i18n';
import { contact,getPage,href,media,imageAlt,type ContentPage,type Block } from '@/lib/content';
import {MegaNav,SiteSearch} from './navigation';
import {ThemeToggle,QuickContact} from './experience';
import {JournalCard} from './journal-browser';
import {summarize} from './journal';
import {designCopy} from '@/lib/design-copy';
import { LanguagePicker,MobileMenu,FAQ,ProjectGrid } from './site-interactions';
export function Picture({name,lang,className='',priority=false,sizes='(max-width: 768px) 95vw, 50vw'}:{name:string;lang:Lang;className?:string;priority?:boolean;sizes?:string}){const im=media[name];return <img className={className} src={im.src} srcSet={im.srcSet} sizes={sizes} width={im.width} height={im.height} alt={name==='cabin-needs'?getPage('melting',lang).title:imageAlt(name==='piping-enhanced'?'1-44-kspMeuvS':name==='steel-enhanced'?'1-27-ceoK89re':name,lang)} loading={priority?'eager':'lazy'} fetchPriority={priority?'high':undefined} decoding="async"/>}
export function Logo({lang}:{lang:Lang}){return <a className="brand" href={href('home',lang)} title={copy[lang].home}><img className="brand-emblem" src="/media/brand/mark.webp" alt="" width={48} height={48}/><span className="brand-wordmark">MAB<small>TEKNOLOJİ</small></span></a>}
export function Header({lang,id}:{lang:Lang;id:string}){const t=copy[lang];return <><a className="skip-link" href="#main">{t.skip}</a><header className="site-header"><Logo lang={lang}/><MegaNav lang={lang} id={id}/><div className="header-actions"><SiteSearch lang={lang}/><ThemeToggle lang={lang}/><LanguagePicker lang={lang} id={id}/><a className="button dark small header-quote" href={href('quote',lang)}>{t.quote}<ArrowUpRight size={15}/></a><MobileMenu lang={lang} id={id}/></div></header></>}
export function CTA({lang}:{lang:Lang}){const t=copy[lang];return <section className="cta-banner outer"><div className="cta-copy"><span className="eyebrow">MAB TEKNOLOJİ</span><h2>{t.ctaTitle}</h2><p>{t.ctaLead}</p><a className="button yellow" href={href('contact',lang)}>{t.contact}<ArrowUpRight size={17}/></a></div><Picture name="1-11-6FCPOeYc" lang={lang}/></section>}
export function Footer({lang}:{lang:Lang}){const t=copy[lang];return <footer className="site-footer container"><div className="footer-main"><div><Logo lang={lang}/><p>{t.footerLine}</p></div><nav aria-label={t.sitemap}>{['about','services','projects','solutions','blog','contact'].map(k=><a key={k} href={href(k,lang)}>{t[k as keyof typeof t]}</a>)}</nav><div className="footer-contact"><a href={`tel:${contact.tel}`}><Phone size={16}/><bdi>{contact.phone}</bdi></a><a href={`mailto:${contact.email}`}><Mail size={16}/><bdi>{contact.email}</bdi></a><a href={contact.whatsapp} target="_blank" rel="noopener noreferrer">WhatsApp <ArrowUpRight size={15}/></a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} MAB Teknoloji. {t.rights}</span><nav>{['privacy','kvkk','cookies'].map(k=><a key={k} href={href(k,lang)}>{t[k as keyof typeof t]}</a>)}</nav></div></footer>}
export function Layout({lang,id,children,cta=true}:{lang:Lang;id:string;children:React.ReactNode;cta?:boolean}){return <><Header lang={lang} id={id}/><main id="main" tabIndex={-1}>{children}</main>{cta&&id!=='contact'&&<CTA lang={lang}/>}<Footer lang={lang}/><QuickContact lang={lang}/></>}
export function SectionHeading({kicker,title,description}:{kicker:string;title:string;description?:string}){return <div className="section-heading"><div><span className="eyebrow">{kicker}</span><h2>{title}</h2></div>{description&&<p>{description}</p>}</div>}
export function Home({lang,page,all}:{lang:Lang;page:ContentPage;all:ContentPage[]}){const t=copy[lang],d=designCopy(lang);const get=(id:string)=>all.find(p=>p.id===id&&p.lang===lang)||getPage(id,lang);const about=get('about');const sectorIcons=[FlaskConical,Container,Wheat,Zap,Factory];const valueIcons=[Ruler,Layers,ShieldCheck,Settings2];return <>
 <section className="hero-intro container"><div className="hero-orbit" aria-hidden="true"/><span className="hero-kicker"><span/> {t.industry}</span><h1>{page.title.split("\n").map((line,i)=><span className={i===1?"hero-title-line hero-highlight":"hero-title-line"} key={i}>{line}</span>)}</h1><p>{page.description}</p><div className="intro-actions"><a className="button dark" href={href('services',lang)}>{t.explore}<ArrowUpRight size={18}/></a><a className="button outline" href={href('quote',lang)}>{leadCopy(lang).entry}<ArrowUpRight size={18}/></a></div></section><section className="hero-showcase outer"><Picture name="piping-enhanced" lang={lang} priority sizes="100vw"/><div className="showcase-caption"><span className="eyebrow">{d.fieldNotes}</span><a href={href('stainless',lang)}>{get('stainless').title}<ArrowUpRight size={27}/></a></div><div className="showcase-facts"><div><strong><bdi>20+</bdi></strong><span>{t.founderExperience}</span></div><div><strong><bdi>2023</bdi></strong><span>{t.founded} · {t.april.split(' ')[0]}</span></div></div></section>
 <section className="sector-strip container"><p>{t.sectorIntro}</p><div>{t.sectors.split('|').map((s,i)=>{const Icon=sectorIcons[i];return <span key={s}><Icon strokeWidth={1.2}/>{s}</span>})}</div></section>
 <section className="container section about-section"><SectionHeading kicker={t.aboutKicker} title={t.aboutTitle} description={t.aboutLead}/><div className="values-grid"><div className="values-photo"><Picture name="1-11-6FCPOeYc" lang={lang}/><span className="image-tag">MAB TEKNOLOJİ</span><div><h3>{t.valuesTitle}</h3><a href={href('about',lang)}>{t.aboutLink}<ArrowUpRight size={19}/></a></div></div><div className="value-cards">{about.values.map((v,i)=>{const Icon=valueIcons[i]||Settings2;return <article key={v.title} className={`value-card value-${i}`}><Icon size={23} strokeWidth={1.3}/><h3>{v.title}</h3><p>{v.description}</p></article>})}</div></div></section>
 <section className="expertise-section container section"><SectionHeading kicker={t.serviceKicker} title={t.serviceTitle} description={t.serviceLead}/><div className="expertise-grid">{['piping','thermal','melting'].map((id,i)=>{const p=get(id);return <article className="expertise-card" key={id}><a className="expertise-photo" href={p.path}><Picture name={i===0?'1-44-kspMeuvS':i===1?'1-11-6FCPOeYc':'cabin-needs'} lang={lang}/><span className="expertise-number">0{i+1}</span><span className="expertise-icon"><ArrowUpRight size={24}/></span></a><div className="expertise-copy"><h3><a href={p.path}>{p.title}</a></h3><p>{p.description}</p><a className="text-link" href={p.path}>{t.details}<ArrowUpRight size={17}/></a></div></article>})}</div><div className="expertise-bottom"><p>{page.blocks[0]?.text||t.serviceLead}</p><a className="button outline" href={href('services',lang)}>{t.allServices}<ArrowRight size={18}/></a></div></section>
 <section className="container section project-section"><SectionHeading kicker={t.projectKicker} title={t.projectTitle} description={t.projectLead}/><ProjectGrid items={['stainless','coil','steel'].map(get)} lang={lang}/><a className="text-link section-link" href={href('projects',lang)}>{t.allProjects}<ArrowRight size={18}/></a></section>
 <section className="method-section container"><SectionHeading kicker={d.approach} title={d.method} description={d.methodLead}/><div className="method-grid">{t.processSteps.split('|').map((step,i)=><article key={step}><span>0{i+1}</span><h3>{step}</h3><ArrowUpRight size={22}/></article>)}</div></section>
 <section className="container solution-band"><div className="solution-number" aria-hidden="true">↗</div><div><span className="eyebrow">{t.solutionKicker}</span><h2>{t.solutionTitle}</h2></div><div><p>{t.solutionLead}</p><a className="text-link" href={href('melting',lang)}>{t.details}<ArrowUpRight size={18}/></a></div></section>
 <section id="faq" className="container section faq-section"><SectionHeading kicker={t.faq} title={t.faqTitle} description={t.faqLead}/><div className="faq-layout"><FAQ lang={lang}/><div className="faq-image"><Picture name="steel-enhanced" lang={lang}/><a className="text-link" href={href('survey',lang)}>{t.survey}<ArrowUpRight size={18}/></a></div></div></section>
 <section className="industry-ideas container"><SectionHeading kicker={t.industry} title={d.ideasTitle} description={d.ideasLead}/><div className="idea-grid">{[{title:d.idea1,text:d.idea1Text,url:href('survey',lang)+'?service=piping'},{title:d.idea2,text:d.idea2Text,url:href('thermal',lang)},{title:d.idea3,text:d.idea3Text,url:href('melting',lang)+'#needs'}].map((x,i)=><a href={x.url} className="industry-idea" key={x.title}><span>0{i+1}<ArrowUpRight size={20}/></span><h3>{x.title}</h3><p>{x.text}</p></a>)}</div></section>
 <section className="container home-journal"><SectionHeading kicker="MAB JOURNAL" title={d.latest} description={t.blogLead}/><div className="journal-grid">{all.filter(p=>p.kind==='article'&&p.lang===lang&&p.status==='published').slice(0,3).map(p=><JournalCard key={p.id} item={summarize(p,all)} lang={lang}/>)}</div><a href={href('blog',lang)} className="text-link section-link">{d.all}<ArrowUpRight size={17}/></a></section>
 </>}
export function PageHeading({page,kicker}:{page:ContentPage;kicker?:string}){const t=copy[page.lang];return <div className="container page-heading"><nav aria-label={t.sitemap} className="breadcrumb"><a href={href('home',page.lang)}>{t.home}</a><span>/</span><span>{page.title}</span></nav><span className="eyebrow">{kicker||t.industry}</span><h1>{page.title}</h1><p>{page.description}</p></div>}
export function Prose({blocks}:{blocks:Block[]}){return <div className="prose">{blocks.map((b,i)=>b.type==='h2'?<h2 key={i} id={`section-${i}`}>{b.text}</h2>:b.type==='h3'?<h3 key={i}>{b.text}</h3>:b.type==='list'?<ul key={i}>{b.items?.map(x=><li key={x}>{x}</li>)}</ul>:<p key={i}>{b.text}</p>)}</div>}
export function ContactAside({lang,service='',project=''}:{lang:Lang;service?:string;project?:string}){const t=copy[lang];const query=new URLSearchParams();if(service)query.set('service',service);if(project)query.set('project',project);return <aside className="contact-aside"><span className="eyebrow">{t.direct}</span><h3>{t.ctaTitle}</h3><p>{t.ctaLead}</p><a className="button yellow" href={`${href('quote',lang)}?${query}`}>{t.quote}<ArrowUpRight size={17}/></a><a className="button outline" href={`${href('survey',lang)}?${query}`}>{t.survey}<ArrowUpRight size={17}/></a><hr/><a href={`tel:${contact.tel}`}><Phone size={16}/><bdi>{contact.phone}</bdi></a><a href={`mailto:${contact.email}`}><Mail size={16}/><bdi>{contact.email}</bdi></a><a href={contact.whatsapp} rel="noopener noreferrer" target="_blank">WhatsApp<ArrowUpRight size={16}/></a></aside>}
