'use client';
import {useRef,useState} from 'react';
import {ArrowRight,ArrowLeft,Check,Printer,Factory,Flame,Box} from 'lucide-react';
import {leadCopy} from '@/lib/lead-copy';
import {getPage,href} from '@/lib/client-content';
import type {Lang} from '@/lib/i18n';
import {RequestForm} from './request-form';
const services=['piping','thermal','melting'] as const;
export function TechnicalBrief({lang,kind,service='',project='',needs='',enabled}:{lang:Lang;kind:'quote'|'survey';service?:string;project?:string;needs?:string;enabled:boolean}){
 const t=leadCopy(lang);const [step,setStep]=useState(0);const [selected,setSelected]=useState(services.includes(service as typeof services[number])?service:'');const [work,setWork]=useState(3);const [details,setDetails]=useState({medium:'',target:'',timing:''});const [docs,setDocs]=useState<number[]>([]);const [owners,setOwners]=useState([0,0,0,0,0]);const heading=useRef<HTMLHeadingElement>(null);const steps=t.steps.split('|'),tasks=t.tasks.split('|'),options=t.owners.split('|');
 const serviceTitle=selected?getPage(selected,lang).title:t.unknown;
 const lines=[`${t.service}: ${serviceTitle}`,`${t.work}: ${t.works.split('|')[work]}`,...(['medium','target','timing'] as const).map(k=>`${t[k]}: ${details[k]||t.unknown}`),`${t.documents}: ${docs.length?docs.map(i=>t.docs.split('|')[i]).join(', '):t.unknown}`,...tasks.map((task,i)=>`${task}: ${options[owners[i]]}`),...(needs?[needs]:[])];
 const summary=lines.join('\n').slice(0,4000);
 function go(value:number){setStep(value);requestAnimationFrame(()=>{heading.current?.focus();heading.current?.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})})}
 return <section className="technical-brief"><div className="brief-intro"><span className="eyebrow">MAB / {kind==='survey'?getPage('survey',lang).title:getPage('quote',lang).title}</span><h2 ref={heading} tabIndex={-1}>{t.title}</h2><p>{t.lead}</p><ol className="brief-steps" aria-label={t.summary}>{steps.map((s,i)=><li key={s} aria-current={step===i?'step':undefined}><span>{step>i?<Check size={14}/>:i+1}</span>{s}</li>)}</ol></div>
 <div hidden={step!==0} className="brief-step"><h3>{t.service}</h3><div className="brief-services" role="group" aria-label={t.service}>{services.map((s,i)=>{const Icon=[Factory,Flame,Box][i];return <button type="button" key={s} aria-pressed={selected===s} onClick={()=>setSelected(s)}><Icon size={25}/><span>{getPage(s,lang).title}</span>{selected===s&&<Check size={17}/>}</button>})}</div><label className="field">{t.work}<select value={work} onChange={e=>setWork(Number(e.target.value))}>{t.works.split('|').map((w,i)=><option key={w} value={i}>{w}</option>)}</select></label><button type="button" className="button dark" onClick={()=>go(1)}>{t.next}<ArrowRight size={17}/></button></div>
 <div hidden={step!==1} className="brief-step"><h3>{steps[1]}</h3><p className="form-note">{t.optional}</p><div className="form-grid">{(['medium','target','timing'] as const).map(k=><label className="field" key={k}>{t[k]}<input value={details[k]} maxLength={180} placeholder={t.unknown} onChange={e=>setDetails({...details,[k]:e.target.value})}/></label>)}</div><fieldset className="brief-docs"><legend>{t.documents}</legend>{t.docs.split('|').map((d,i)=><label key={d}><input type="checkbox" checked={docs.includes(i)} onChange={e=>setDocs(e.target.checked?[...docs,i]:docs.filter(x=>x!==i))}/>{d}</label>)}</fieldset><div className="brief-controls"><button type="button" className="button outline" onClick={()=>go(0)}><ArrowLeft size={17}/>{t.back}</button><button type="button" className="button dark" onClick={()=>go(2)}>{t.next}<ArrowRight size={17}/></button></div></div>
 <div hidden={step!==2} className="brief-step"><h3>{t.scope}</h3><p className="form-note">{t.scopeNote}</p><div className="scope-matrix">{tasks.map((task,i)=><label className="field" key={task}><span>{task}</span><select value={owners[i]} onChange={e=>setOwners(owners.map((x,j)=>i===j?Number(e.target.value):x))}>{options.map((o,k)=><option value={k} key={o}>{o}</option>)}</select></label>)}</div><div className="brief-controls"><button type="button" className="button outline" onClick={()=>go(1)}><ArrowLeft size={17}/>{t.back}</button><button type="button" className="button dark" onClick={()=>go(3)}>{t.next}<ArrowRight size={17}/></button></div></div>
 <section className="brief-summary" hidden={step<2}><div><span className="eyebrow">MAB TEKNOLOJİ</span><h3>{t.summary}</h3></div><dl>{lines.map((line,i)=>{const colon=line.indexOf(':');return <div key={i}><dt>{colon>=0?line.slice(0,colon):''}</dt><dd>{colon>=0?line.slice(colon+1).trim():line}</dd></div>})}</dl><p>{t.scopeNote}</p><button type="button" className="text-link" onClick={()=>window.print()}><Printer size={16}/>{t.print}</button></section>
 <div hidden={step!==3} className="brief-step brief-contact"><div className="brief-contact-heading"><p>{t.ready}</p><button type="button" className="text-link" onClick={()=>go(2)}>{t.edit}</button></div><RequestForm lang={lang} kind={kind} service={selected} project={project} needs={summary} enabled={enabled} showContext={false}/></div>
 <div className="brief-direct"><a href={href('contact',lang)}>{t.quick}<ArrowRight size={16}/></a></div></section>
}
