import original from '@/content/source.json';
import rawMedia from '@/content/media.json';
import blog from '@/content/blog.json';
import { copy,languages,type Lang } from './i18n';
import {designCopy} from './design-copy';
import {legalBlocks} from './legal';
export type Block={type:string;text?:string;items?:string[]};
export type ContentPage={id:string;kind:string;lang:Lang;path:string;source:string;title:string;description:string;blocks:Block[];images:{key:string;alt:string;caption:string}[];tables:string[][][];options:{title:string;description:string;items:string[]}[];values:{title:string;description:string}[];meta:{key:string;value:string}[];seoTitle:string;status:'published'|'draft';modified:string;sources?:{title:string;url:string}[];related?:string;reviewed?:boolean};
const empty={source:'',blocks:[],images:[],tables:[],options:[],values:[],meta:[],modified:'2026-09-13'};
const added=languages.flatMap(lang=>['solutions','blog','sitemap','privacy','kvkk','cookies'].map(id=>({ ...empty,id,lang,kind:id,path:`/${lang}/${lang==='tr'?({solutions:'ozel-cozumler',sitemap:'site-haritasi',privacy:'gizlilik',cookies:'cerez-politikasi'} as Record<string,string>)[id]||id:id}`,title:copy[lang][id as keyof typeof copy.tr],description:id==='blog'?copy[lang].blogLead:id==='solutions'?copy[lang].solutionLead:copy[lang][id as keyof typeof copy.tr]+' — MAB Teknoloji',seoTitle:copy[lang][id as keyof typeof copy.tr]+' — MAB Teknoloji',status:['privacy','kvkk','cookies'].includes(id)?'draft':'published'})));
export const pages=([...original,...added,...blog] as ContentPage[]).map(p=>p.id==='home'?{...p,title:designCopy(p.lang).heroTitle,description:copy[p.lang].heroLead,blocks:[{type:'p',text:p.description},...p.blocks]}:['privacy','kvkk','cookies'].includes(p.id)?{...p,blocks:legalBlocks(p.lang,p.id)}:p);
export const getPage=(id:string,lang:Lang)=>pages.find(p=>p.id===id&&p.lang===lang)!;
export const href=(id:string,lang:Lang)=>getPage(id,lang)?.path||`/${lang}`;
export const findPage=(path:string)=>pages.find(p=>p.path===path);
export const media=rawMedia as Record<string,{src:string;srcSet:string;width:number;height:number;source:string;original:string}>;
export const mediaKeys=['1-44-kspMeuvS','1-38-pvQ8DSzu','1-27-ceoK89re','1-11-6FCPOeYc','1-12-LSRvMWXf','1-14-swPI4ROa','1-41-trk2Yeua','1-29-d4pyra1Y'];
export const imageAlt=(key:string,lang:Lang)=>copy[lang].imageAlts.split('|')[mediaKeys.indexOf(key)]||copy[lang].gallery;
export const projectYear=(p:ContentPage)=>p.id==='stainless'?'2024':'2023';
export const projectCategory=(p:ContentPage)=>p.meta[0]?.value||getPage('piping',p.lang).title;
export const contact={phone:'+90 544 453 41 63',tel:'+905444534163',email:'info@mabteknoloji.com.tr',whatsapp:'https://wa.me/905444534163'};
export const ORIGIN='https://mabteknoloji.com.tr';
