import {chromium,expect} from '@playwright/test';
import fs from 'node:fs';
const BASE='http://localhost:5173';const browser=await chromium.launch();const context=await browser.newContext();const page=await context.newPage();const result=[];
const record=(test,pass,detail='')=>{result.push({test,pass,detail});console.log(`${pass?'PASS':'FAIL'} ${test}`)};
await page.goto(BASE+'/tr/teklif-al?service=piping',{waitUntil:'networkidle'});
await expect(page.locator('input[name=name]')).toBeVisible();
for(const [name,value]of Object.entries({name:'MAB Local QA',email:'mab-qa@example.test',phone:'+90 555 000 0000',message:'LOCAL TEST ONLY — no real company contact.'}))await page.locator(`[name="${name}"]`).fill(value);
await page.locator('[name=consent]').check();await page.waitForTimeout(1500);await page.locator('button[type=submit]').click();await expect(page.locator('.form-status.success')).toBeVisible({timeout:25000});
record('Valid form delivered to LOCAL test sink',true);
await page.goto(BASE+'/tr/teklif-al',{waitUntil:'networkidle'});
for(const [name,value]of Object.entries({name:'MAB Failure QA',email:'mab-failure@example.test',phone:'+90 555 000 0001',message:'LOCAL TEST ONLY — injected delivery failure.'}))await page.locator(`[name="${name}"]`).fill(value);
await page.locator('[name=consent]').check();await context.request.post('http://127.0.0.1:5190/fail-next');await page.waitForTimeout(1500);await page.locator('button[type=submit]').click();await expect(page.locator('[role=alert]')).toBeVisible({timeout:25000});record('Delivery failure is visible and preserves user input',(await page.locator('[name=name]').inputValue())==='MAB Failure QA'&&await page.locator('.form-status.success').count()===0);
const token=await context.request.get(BASE+'/api/request-token').then(r=>r.json());await page.waitForTimeout(1500);
const valid={lang:'en',kind:'quote',name:'API Local Test',email:'test@example.test',phone:'05550000000',company:'',role:'',location:'',date:'',channel:'',service:'piping',project:'',message:'Local backend validation exercise only.',needs:'',consent:'on',website:'',token:token.token,requestId:crypto.randomUUID()};
const send=(body,origin=BASE)=>context.request.post(BASE+'/api/requests',{headers:{Origin:origin},multipart:body});
record('Cross-origin POST rejected',(await send(valid,'https://example.invalid')).status()===403);
record('Invalid email rejected',(await send({...valid,email:'invalid'})).status()===400);
record('Missing acknowledgement rejected',(await send({...valid,consent:''})).status()===400);
record('Honeypot rejected',(await send({...valid,website:'spam'})).status()===400);
record('Forged timing token rejected',(await send({...valid,token:'123.invalid.invalid'})).status()===400);
const badFile=await send({...valid,file:{name:'bad.png',mimeType:'image/png',buffer:Buffer.from('<script>bad</script>')}});record('Forged file signature rejected',badFile.status()===400);
const upload=await send({...valid,requestId:crypto.randomUUID(),file:{name:'qa.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\n% local test attachment\n%%EOF')}});const uploaded=await upload.json();record('Permitted attachment stored privately',upload.status()===200);
record('Private attachment unauthenticated denied',(await context.request.get(BASE+'/api/admin/attachment/'+uploaded.id)).status()===403);
const again=await send({...valid,requestId:uploaded.id});record('Idempotent successful retry',again.status()===200);
let limited=false;for(let i=0;i<6;i++){if((await send({...valid,requestId:crypto.randomUUID()})).status()===429){limited=true;break}}record('Durable rate limit enforced',limited);
await page.goto(BASE+'/signin-with-chatgpt?return_to=/admin',{waitUntil:'networkidle'});await expect(page.locator('h1')).toContainText('İçerik yönetimi');await expect(page.locator('.json-editor')).toBeVisible();
const admin=await context.request.get(BASE+'/api/admin').then(r=>r.json());const entry=admin.entries.find(e=>e.key==='tr:about');const original=entry.draft;const altered={...original,title:'QA DRAFT ONLY — '+original.title};
const save=await context.request.post(BASE+'/api/admin',{headers:{Origin:BASE},data:{key:'tr:about',action:'save',content:altered}});record('Authorized draft save',save.status()===200);
await page.goto(BASE+'/tr/hakkimizda');record('Draft does not replace published page',!(await page.locator('h1').textContent()).includes('QA DRAFT'));
await page.reload();const after=await context.request.get(BASE+'/api/admin').then(r=>r.json());record('Draft persists across requests',after.entries.find(e=>e.key==='tr:about').draft.title===altered.title);
const publish=await context.request.post(BASE+'/api/admin',{headers:{Origin:BASE},data:{key:'tr:about',action:'publish',content:altered}});await page.goto(BASE+'/tr/hakkimizda');record('Publish changes SSR content',publish.status()===200&&(await page.locator('h1').textContent()).includes('QA DRAFT'));
await context.request.post(BASE+'/api/admin',{headers:{Origin:BASE},data:{key:'tr:about',action:'publish',content:original}});
const article=admin.entries.find(e=>e.draft.kind==='article');const unapproved=await context.request.post(BASE+'/api/admin',{headers:{Origin:BASE},data:{key:article.key,action:'publish',content:{...article.draft,reviewed:false}}});record('Technical approval required before publishing draft',unapproved.status()===400);
record('Private attachment authorized download',(await context.request.get(BASE+'/api/admin/attachment/'+uploaded.id)).status()===200);
await browser.close();fs.writeFileSync('reports/backend-tests.json',JSON.stringify({date:new Date().toISOString(),delivery:'LOCAL TEST SINK ONLY — NO EXTERNAL EMAIL',tests:result},null,2));console.log(JSON.stringify({checks:result.length,failures:result.filter(x=>!x.pass)},null,2));
