from pathlib import Path
p=Path('components/site.tsx');s=p.read_text(encoding='utf8');s=s.replace("import { LanguagePicker", "import {MegaNav,SiteSearch} from './navigation';\nimport {ThemeToggle,QuickContact} from './experience';\nimport {JournalCard} from './journal-browser';\nimport {summarize} from './journal';\nimport {designCopy} from '@/lib/design-copy';\nimport { LanguagePicker")
lines=s.splitlines()
for i,line in enumerate(lines):
 if line.startswith('export function Logo('):lines[i]='''export function Logo({lang}:{lang:Lang}){return <a className="brand" href={href('home',lang)} aria-label={`MAB TEKNOLOJİ · ${copy[lang].home}`}><img className="brand-emblem" src="/media/brand/mark.webp" alt="" width={48} height={48}/><span className="brand-wordmark">MAB<small>TEKNOLOJİ</small></span></a>}'''
 if line.startswith('export function Header('):lines[i]='''export function Header({lang,id}:{lang:Lang;id:string}){const t=copy[lang];return <><a className="skip-link" href="#main">{t.skip}</a><header className="site-header"><Logo lang={lang}/><MegaNav lang={lang} id={id}/><div className="header-actions"><SiteSearch lang={lang}/><ThemeToggle lang={lang}/><LanguagePicker lang={lang} id={id}/><a className="button dark small header-quote" href={href('quote',lang)}>{t.quote}<ArrowUpRight size={15}/></a><MobileMenu lang={lang} id={id}/></div></header></>}'''
 if line.startswith('export function Layout('):lines[i]=line.replace('<Footer lang={lang}/>','<Footer lang={lang}/><QuickContact lang={lang}/>')
 if line.startswith('export function Footer('):lines[i]=line.replace('<div className="footer-bottom">','<div className="footer-signature" aria-hidden>MAB<span>®</span></div><div className="footer-bottom">')
 if line.startswith('export function Home('):lines[i]=line.replace('const t=copy[lang];','const t=copy[lang],d=designCopy(lang);')
 if '<section className="hero outer">' in line:lines[i]=''' <section className="hero-intro container"><div className="hero-orbit" aria-hidden/><span className="hero-kicker"><span/> {t.industry}</span><h1>{page.title}</h1><p>{page.description}</p><div className="intro-actions"><a className="button dark" href={href('services',lang)}>{t.explore}<ArrowUpRight size={18}/></a><a className="button outline" href={href('survey',lang)}>{t.survey}<ArrowUpRight size={18}/></a></div></section><section className="hero-showcase outer"><Picture name="piping-enhanced" lang={lang} priority sizes="100vw"/><div className="showcase-caption"><span className="eyebrow">{d.fieldNotes}</span><a href={href('stainless',lang)}>{get('stainless').title}<ArrowUpRight size={27}/></a></div><div className="showcase-facts"><div><strong><bdi>20+</bdi></strong><span>{t.founderExperience}</span></div><div><strong><bdi>2023</bdi></strong><span>{t.founded} · {t.april.split(' ')[0]}</span></div></div></section>'''
 if '<section className="container section faq-section">' in line:lines[i]=line.replace('<section className="container section faq-section">','<section id="faq" className="container section faq-section">').replace('name="1-27-ceoK89re"','name="steel-enhanced"')
s='\n'.join(lines)+'\n';s=s.replace("alt={imageAlt(name,lang)}", "alt={imageAlt(name==='piping-enhanced'?'1-44-kspMeuvS':name==='steel-enhanced'?'1-27-ceoK89re':name,lang)}")
s=s.replace(' <section className="container solution-band">',''' <section className="method-section container"><SectionHeading kicker={d.approach} title={d.method} description={d.methodLead}/><div className="method-grid">{t.processSteps.split('|').map((step,i)=><article key={step}><span>0{i+1}</span><h3>{step}</h3><ArrowUpRight size={22}/></article>)}</div></section>
 <section className="container solution-band">''')
s=s.replace(' </>}',' </>}')
needle='\n </>}\nexport function PageHeading'
addition='''
 <section className="container home-journal"><SectionHeading kicker="MAB JOURNAL" title={d.latest} description={t.blogLead}/><div className="journal-grid">{all.filter(p=>p.kind==='article'&&p.lang===lang&&p.status==='published').slice(0,3).map(p=><JournalCard key={p.id} item={summarize(p,all)} lang={lang}/>)}</div><a href={href('blog',lang)} className="text-link section-link">{d.all}<ArrowUpRight size={17}/></a></section>'''
s=s.replace(needle,addition+needle)
p.write_text(s,encoding='utf8')
p=Path('components/content-pages.tsx');s=p.read_text(encoding='utf8');s=s.replace("import {legalBlocks}","import {JournalIndex,JournalArticle} from './journal';\nimport {legalBlocks}")
s=s.replace(' return <><PageHeading page={page}/>',' if(page.id===\'blog\')return <JournalIndex page={page} all={all}/>;\n if(page.kind===\'article\')return <JournalArticle page={page} all={all}/>;\n return <><PageHeading page={page}/>')
s='\n'.join(line for line in s.splitlines() if not line.startswith(" {page.id==='blog'&&") and not line.startswith(" {page.kind==='article'&&"))+'\n';p.write_text(s,encoding='utf8')
p=Path('lib/content.ts');s=p.read_text(encoding='utf8').replace("import {legalBlocks}","import {designCopy} from './design-copy';\nimport {legalBlocks}").replace('title:copy[p.lang].hero,description','title:designCopy(p.lang).heroTitle,description');p.write_text(s,encoding='utf8')
p=Path('scripts/build-editorial.mjs');s=p.read_text(encoding='utf8').replace("images:[]","images:[{key:a.id,alt:a.titles[i],caption:''}]").replace("status:'draft',modified:'2026-09-13'","status:'published',modified:'2026-09-14'").replace('reviewed:false','reviewed:true');p.write_text(s,encoding='utf8')
