from pathlib import Path
p=Path('components/experience.tsx');s=p.read_text(encoding='utf8').replace('mab-theme-v2','mab-theme-v3');a=s.index('export function Experience(');b=s.index('export function QuickContact(',a)
s=s[:a]+'''export function Experience({lang}:{lang:Lang}){const t=designCopy(lang);
 useEffect(()=>{let navigateTimer:ReturnType<typeof setTimeout>,escapeTimer:ReturnType<typeof setTimeout>;const clear=()=>{delete document.documentElement.dataset.navigating;clearTimeout(navigateTimer);clearTimeout(escapeTimer)};const click=(e:MouseEvent)=>{if(e.defaultPrevented||e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;const a=(e.target as HTMLElement)?.closest('a');if(!a||a.hasAttribute('download')||(a.target&&a.target!=='_self'))return;const url=new URL(a.href,location.href);if(url.origin!==location.origin||url.protocol!==location.protocol||(url.pathname===location.pathname&&url.search===location.search))return;e.preventDefault();document.documentElement.dataset.navigating='true';clearTimeout(navigateTimer);navigateTimer=setTimeout(()=>location.assign(url.href),matchMedia('(prefers-reduced-motion: reduce)').matches?0:220);escapeTimer=setTimeout(clear,10000)};document.addEventListener('click',click);window.addEventListener('pageshow',clear);return()=>{clear();document.removeEventListener('click',click);window.removeEventListener('pageshow',clear)}},[]);
 useEffect(()=>{const reduce=matchMedia('(prefers-reduced-motion: reduce)');let frame=0;const scroll=()=>{if(frame)return;frame=requestAnimationFrame(()=>{frame=0;document.documentElement.dataset.scrolled=String(scrollY>30);const hero=document.querySelector('.hero-intro');if(hero&&!reduce.matches){const r=hero.getBoundingClientRect();const v=Math.min(1,Math.max(0,-r.top/Math.max(1,r.height)));(hero as HTMLElement).style.setProperty('--scroll-blur',`${(v*5).toFixed(2)}px`);(hero as HTMLElement).style.setProperty('--scroll-fade',String(1-v*.3))}})};const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){e.target.classList.add('revealed');observer.unobserve(e.target)}},{threshold:.08});document.querySelectorAll('.expertise-card,.industry-idea,.journal-card,.contact-studio-info,.method-grid article,.section-heading').forEach((el,i)=>{(el as HTMLElement).style.setProperty('--reveal-delay',`${(i%3)*75}ms`);observer.observe(el)});window.addEventListener('scroll',scroll,{passive:true});scroll();return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',scroll);observer.disconnect()}},[]);
 return <div className="page-loader" role="status" aria-live="polite"><div className="loader-emblem"><img src="/media/brand/mark.webp" alt="" width={72} height={72}/><span/></div><strong>MAB <span>TEKNOLOJİ</span></strong><p>{t.loading}</p><div className="loader-line"><span/></div><small>{t.introLine}</small></div>
}
''' + s[b:];p.write_text(s,encoding='utf8')
p=Path('app/layout.tsx');s=p.read_text(encoding='utf8').replace("import './redesign.css';","import './redesign.css';\nimport './revision-v3.css';");a=s.index('const bootstrap=');b=s.index('export default',a)
s=s[:a]+'''const bootstrap=`(()=>{const r=document.documentElement;try{r.dataset.theme=localStorage.getItem('mab-theme-v3')==='dark'?'dark':'light'}catch{r.dataset.theme='light'}r.dataset.intro='show';const finish=()=>setTimeout(()=>delete r.dataset.intro,matchMedia('(prefers-reduced-motion: reduce)').matches?120:700);if(document.readyState==='complete')finish();else addEventListener('load',finish,{once:true});setTimeout(()=>delete r.dataset.intro,4500);addEventListener('pageshow',e=>{if(e.persisted){delete r.dataset.intro;delete r.dataset.navigating}})})()`;
''' + s[b:];p.write_text(s,encoding='utf8')
