from pathlib import Path
p=Path('lib/design-copy.ts');s=p.read_text(encoding='utf8').replace('const rows={','''const rows={
contactTitle:['Bir ihtiyacınız var.\\nBirlikte netleştirelim.','Your next project.\\nLet’s make it clear.','مشروعك القادم.\\nلنحدد احتياجاته معًا.','Ваш следующий проект.\\nОбсудим детали.'],
contactLead:['Tesisinizi, sürecinizi ve hedefinizi anlatın. Doğru başlangıç, iyi bir görüşmeyle olur.','Tell us about your facility, process and goals. A good conversation is the first step.','حدثنا عن منشأتك وعملياتك وأهدافك. الحوار الجيد هو الخطوة الأولى.','Расскажите об объекте, процессе и целях. Хороший разговор — первый шаг.'],
mailDraft:['E-posta taslağı hazırla','Prepare email draft','إعداد مسودة بريد','Подготовить письмо'],
mailHint:['Bilgileriniz e-posta uygulamanızda taslak olarak açılır. Gönderimi oradan tamamlarsınız.','Your details open as a draft in your email app. Send the message from there.','تُفتح بياناتك كمسودة في تطبيق البريد؛ أرسل الرسالة من هناك.','Данные откроются в черновике почтового приложения. Отправьте письмо оттуда.'],
mailReady:['E-posta taslağı hazırlandı. Gönderimi e-posta uygulamanızdan tamamlayın.','Email draft prepared. Complete sending in your email app.','تم إعداد المسودة. أكمل الإرسال من تطبيق البريد.','Черновик подготовлен. Завершите отправку в почтовом приложении.'],
chooseLanguage:['Görüntüleme dili','Display language','لغة العرض','Язык сайта'],
ideasTitle:['Tesisinizin sıradaki adımı.','The next step for your facility.','الخطوة التالية لمنشأتك.','Следующий шаг для вашего объекта.'],
ideasLead:['Sahadaki gerçek ihtiyaçlardan başlayan üç görüşme konusu.','Three conversations that start with real site needs.','ثلاثة محاور تبدأ من احتياجات الموقع الفعلية.','Три темы, основанные на реальных потребностях объекта.'],
idea1:['Planlı duruşa hazırlık','Preparing for a shutdown','الاستعداد للتوقف المخطط','Подготовка к плановому останову'],
idea1Text:['İş kapsamı, saha erişimi ve montaj sırasını duruş öncesinde birlikte netleştirelim.','Clarify scope, site access and installation sequence before the shutdown.','حدد نطاق العمل والوصول للموقع وتسلسل التركيب قبل التوقف.','Уточним объём, доступ к площадке и порядок монтажа до останова.'],
idea2:['Buhar ve kondens değerlendirmesi','Steam and condensate review','تقييم البخار والمكثفات','Оценка пара и конденсата'],
idea2Text:['Mevcut hat bilgileri ve proses ihtiyaçlarıyla teknik değerlendirme dosyanızı hazırlayın.','Prepare a review brief with existing line data and process needs.','جهّز ملف التقييم ببيانات الخطوط الحالية واحتياجات العملية.','Подготовьте данные существующих линий и потребности процесса для оценки.'],
idea3:['Hammaddeye özel kabin','A cabin for your raw material','كابينة تناسب المادة الخام','Кабина под ваше сырьё'],
idea3Text:['Hammadde, ambalaj, kapasite ve enerji altyapısını tek ihtiyaç dosyasında toplayın.','Bring material, packaging, capacity and energy infrastructure into one brief.','اجمع بيانات المادة والتعبئة والسعة ومصدر الطاقة في ملف واحد.','Соберите сведения о сырье, упаковке, объёме и энергоснабжении в одном задании.'],
''');p.write_text(s,encoding='utf8')
p=Path('components/site.tsx');s=p.read_text(encoding='utf8').replace('MobileMenu,ServiceAccordion,FAQ','MobileMenu,FAQ').replace('<div className="footer-signature" aria-hidden="true">MAB</div>','');start=s.index(' <section className="service-section outer">');end=s.index(' <section className="container section project-section">',start)
s=s[:start]+''' <section className="expertise-section container section"><SectionHeading kicker={t.serviceKicker} title={t.serviceTitle} description={t.serviceLead}/><div className="expertise-grid">{['piping','thermal','melting'].map((id,i)=>{const p=get(id);return <article className="expertise-card" key={id}><a className="expertise-photo" href={p.path}><Picture name={i===0?'1-44-kspMeuvS':i===1?'1-11-6FCPOeYc':'cabin-needs'} lang={lang}/><span className="expertise-number">0{i+1}</span><span className="expertise-icon"><ArrowUpRight size={24}/></span></a><div className="expertise-copy"><h3><a href={p.path}>{p.title}</a></h3><p>{p.description}</p><a className="text-link" href={p.path}>{t.details}<ArrowUpRight size={17}/></a>{id==='melting'&&<small className="image-credit">{d.editorial}</small>}</div></article>})}</div><div className="expertise-bottom"><p>{page.blocks[0]?.text||t.serviceLead}</p><a className="button outline" href={href('services',lang)}>{t.allServices}<ArrowRight size={18}/></a></div></section>
'''+s[end:]
needle=' <section className="container home-journal">';pos=s.index(needle);s=s[:pos]+''' <section className="industry-ideas container"><SectionHeading kicker={t.industry} title={d.ideasTitle} description={d.ideasLead}/><div className="idea-grid">{[{title:d.idea1,text:d.idea1Text,url:href('survey',lang)+'?service=piping'},{title:d.idea2,text:d.idea2Text,url:href('thermal',lang)},{title:d.idea3,text:d.idea3Text,url:href('melting',lang)+'#needs'}].map((x,i)=><a href={x.url} className="industry-idea" key={x.title}><span>0{i+1}<ArrowUpRight size={20}/></span><h3>{x.title}</h3><p>{x.text}</p></a>)}</div></section>
'''+s[pos:];p.write_text(s,encoding='utf8')
p=Path('components/content-pages.tsx');s=p.read_text(encoding='utf8').replace("import {legalBlocks}","import {designCopy} from '@/lib/design-copy';\nimport {legalBlocks}")
s=s.replace("if(page.id==='blog')",'''if(page.id==='contact'){const d=designCopy(lang);return <><section className="contact-heading container"><span className="eyebrow">{t.contact} / MAB TEKNOLOJİ</span><h1>{d.contactTitle}</h1><p>{d.contactLead}</p></section><section className="contact-studio container"><div className="contact-studio-info"><Picture name="steel-enhanced" lang={lang}/><div className="contact-studio-copy"><span className="eyebrow">{t.direct}</span><h2>{d.startProject}</h2>{[{label:t.phone,value:contact.phone,url:'tel:'+contact.tel,Icon:Phone},{label:t.email,value:contact.email,url:'mailto:'+contact.email,Icon:Mail},{label:'WhatsApp',value:t.write,url:contact.whatsapp,Icon:MessageCircle}].map(x=><a href={x.url} key={x.label}><x.Icon size={20}/><span><small>{x.label}</small><bdi>{x.value}</bdi></span><ArrowUpRight size={20}/></a>)}<small className="image-credit">{d.enhanced}</small></div></div><div className="contact-studio-form"><span className="eyebrow">{t.contact}</span><h2>{d.startProject}</h2><RequestForm lang={lang} kind="contact" enabled={formsEnabled}/></div></section>{page.blocks.length>0&&<section className="container contact-source"><Prose blocks={page.blocks}/></section>}</>}
 if(page.id==='blog')''');p.write_text(s,encoding='utf8')
p=Path('components/request-form.tsx');s=p.read_text(encoding='utf8').replace("import {copy,type Lang}","import {designCopy} from '@/lib/design-copy';\nimport {copy,type Lang}").replace('const t=copy[lang];const [status','const t=copy[lang],d=designCopy(lang);const [status')
s=s.replace("if(!enabled){setStatus('unconfigured');return}",'''if(!enabled){const data=new FormData(e.currentTarget);const fields=['name','company','email','phone','role','location','date','service','message'];const body=fields.filter(k=>data.get(k)).map(k=>`${t[k as keyof typeof t]||k}: ${k==='service'?getPage(String(data.get(k)),lang)?.title||data.get(k):data.get(k)}`).join('\\n')+(project?'\\n'+t.projects+': '+getPage(project,lang).title:'')+(needs?'\\n'+needs:'');window.location.href='mailto:info@mabteknoloji.com.tr?subject='+encodeURIComponent('MAB Teknoloji — '+t[kind])+'&body='+encodeURIComponent(body);setStatus('mailReady');return}''')
s=s.replace('{!enabled&&<div className="form-status info" role="status">{t.unconfigured}</div>}','')
s=s.replace("{kind!=='contact'&&<label className=\"field span-2\">{t.file}","{enabled&&kind!=='contact'&&<label className=\"field span-2\">{t.file}")
s=s.replace("{t[status as keyof typeof t]||t.error}","{status==='mailReady'?d.mailReady:t[status as keyof typeof t]||t.error}").replace("role={status==='success'?'status':'alert'}","role={status==='success'||status==='mailReady'?'status':'alert'}")
s=s.replace('{sending?t.sending:t.send}','{sending?t.sending:enabled?t.send:d.mailDraft}').replace('<div className="span-2"><button className="button yellow"','<div className="span-2">{!enabled&&<p className="form-note mail-compose-note">{d.mailHint}</p>}<button className="button yellow"')
p.write_text(s,encoding='utf8')
p=Path('components/site-interactions.tsx');s=p.read_text(encoding='utf8').replace('Globe,Menu,X,Plus','Globe,Menu,X,Plus,Check,ChevronDown').replace("import { copy,languageNames", "import {designCopy} from '@/lib/design-copy';\nimport { copy,languageNames")
s=s.replace('<span>{lang.toUpperCase()}</span><span aria-hidden>⌄</span>', '<span className="language-current-name">{languageNames[lang]}</span><span className="language-current-code">{lang.toUpperCase()}</span><ChevronDown size={13}/>').replace('<div className="language-options">{languages.map','<div className="language-options"><p>{designCopy(lang).chooseLanguage}</p>{languages.map').replace('{languageNames[l]}<span>{l.toUpperCase()}</span>','<span className="language-option-name">{languageNames[l]}<small>{l.toUpperCase()}</small></span>{lang===l?<Check size={17}/>:<ArrowUpRight size={17}/>}')
p.write_text(s,encoding='utf8')
