import {chromium,expect} from '@playwright/test';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
const base=process.env.TEST_BASE||'http://127.0.0.1:4180',routes=JSON.parse(readFileSync('content/routes.json','utf8')),b=await chromium.launch(),context=await b.newContext(),p=await context.newPage();const errors=[],results=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(15000);mkdirSync('reports/vercel',{recursive:true});
try{
 for(const lang of ['tr','en','ar','ru']){
  await p.setViewportSize({width:390,height:900});await p.goto(base+'/'+lang);await p.waitForFunction(()=>!document.documentElement.dataset.intro);await p.waitForTimeout(500);await p.evaluate(()=>document.fonts.ready);expect(await p.locator('html').getAttribute('lang')).toBe(lang);expect(await p.locator('html').getAttribute('dir')).toBe(lang==='ar'?'rtl':'ltr');expect(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);const lines=await p.locator('.hero-title-line').evaluateAll(elements=>elements.map(e=>{const r=document.createRange();r.selectNodeContents(e);return r.getClientRects().length}));expect(lines).toEqual([1,1]);
  await p.goto(base+routes.find(x=>x.id==='quote'&&x.lang===lang).path+'?service=piping');await p.waitForFunction(()=>!document.documentElement.dataset.intro);await p.waitForTimeout(400);for(let step=0;step<3;step++)await p.locator('.brief-step:visible > .button,.brief-step:visible .brief-controls > .button:last-child').click();await expect(p.locator('.brief-contact')).toBeVisible();await expect(p.locator('select[name=service]')).toHaveValue('piping');expect(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);results.push({lang,heroTwoLines:true,quoteFourSteps:true});
 }
 for(const path of ['/tr/blog','/tr/blog/endustriyel-borulama-proje-planlamasi','/tr/iletisim']){const r=await p.goto(base+path);expect(r.status()).toBe(200);await expect(p.locator('h1')).toHaveCount(1)}
 for(const path of ['/admin','/api/admin','/api/admin/leads']){const r=await fetch(base+path,{headers:{'oai-authenticated-user-id':'local_seedy','oai-authenticated-user-email':'test@example.test'}});expect(r.status).toBe(401)}
 expect((await fetch(base+'/tr/teklif-al?preview=1')).status).toBe(404);const sitemap=await fetch(base+'/sitemap.xml');expect(sitemap.status).toBe(200);expect((await sitemap.text()).match(/<loc>/g).length).toBe(84);expect((await fetch(base+'/not-a-page')).status).toBe(404);expect(errors).toEqual([]);
 await p.setViewportSize({width:1440,height:1000});await p.goto(base+'/tr');await p.waitForFunction(()=>!document.documentElement.dataset.intro);await p.waitForTimeout(450);await p.screenshot({path:'reports/vercel/home.png'});writeFileSync('reports/vercel/browser.json',JSON.stringify({base,results,errors,adminProtected:true,sitemapUrls:84},null,2));console.log('Four languages, two-line mobile hero, quote workflow, blog/contact, admin protection, draft access and 84-URL sitemap passed.');
}finally{await b.close()}
