import {env} from '@/lib/runtime-env';
import {z} from 'zod';
import {adminUser,sameOrigin} from '@/lib/admin';
import {pages,media,type ContentPage} from '@/lib/content';
const fail=(error:string,status:number)=>Response.json({error},{status});
const block=z.object({type:z.enum(['h2','h3','p','li','list']),text:z.string().max(20000).optional(),items:z.array(z.string().max(3000)).max(100).optional()});
const schema=z.object({title:z.string().min(2).max(250),description:z.string().min(10).max(1500),seoTitle:z.string().min(2).max(250),blocks:z.array(block).max(200),images:z.array(z.object({key:z.string().refine(k=>k in media),alt:z.string().max(500),caption:z.string().max(500)})).max(30),tables:z.array(z.array(z.array(z.string().max(3000)).max(15)).max(100)).max(10),options:z.array(z.object({title:z.string().max(250),description:z.string().max(1500),items:z.array(z.string().max(1500)).max(30)})).max(30),values:z.array(z.object({title:z.string().max(250),description:z.string().max(1500)})).max(20),meta:z.array(z.object({key:z.string().max(250),value:z.string().max(500)})).max(30),sources:z.array(z.object({title:z.string().max(250),url:z.string().url().startsWith('https://')})).max(30).optional(),related:z.enum(['piping','thermal','melting']).optional(),reviewed:z.boolean().optional()});
export async function GET(){if(!await adminUser())return fail('Yetkisiz erişim',403);if(!env.DB)return fail('Veritabanı bağlı değil',503);try{const saved=await env.DB.prepare('SELECT key,draft,published,updated FROM documents').all<{key:string;draft:string;published:string|null;updated:string}>();const entries=pages.map(p=>{const row=saved.results.find(x=>x.key===p.lang+':'+p.id);return{key:p.lang+':'+p.id,draft:row?JSON.parse(row.draft):p,published:row?.published?JSON.parse(row.published):p,updated:row?.updated||p.modified}});const requests=await env.DB.prepare('SELECT id,payload,status,filename,created FROM submissions ORDER BY created DESC LIMIT 100').all();return Response.json({entries,requests:requests.results,media:Object.keys(media)})}catch{return fail('Veritabanı okunamadı. Yerel migrasyonları kontrol edin.',503)}}
export async function POST(request:Request){const user=await adminUser();if(!user||!sameOrigin(request))return fail('Yetkisiz erişim',403);if(!env.DB)return fail('Veritabanı bağlı değil',503);if(Number(request.headers.get('content-length')||0)>500000)return fail('İçerik çok büyük',413);try{const input=await request.json() as {key:string;action:string;content:ContentPage};const source=pages.find(p=>p.lang+':'+p.id===input.key);if(!source)return fail('Sayfa bulunamadı',404);if(!['save','publish','unpublish'].includes(input.action))return fail('Geçersiz işlem',400);const parsed=schema.safeParse(input.content);if(!parsed.success)return fail('İçerik alanları geçersiz: '+parsed.error.issues.map(x=>x.path.join('.')).join(', '),400);if(input.action==='publish'&&['article','privacy','kvkk','cookies'].includes(source.kind)&&!parsed.data.reviewed)return fail('Teknik / hukuki inceleme onayını işaretleyin.',400);const now=new Date().toISOString();const status=input.action==='publish'?'published':'draft';const document={...source,...parsed.data,status,modified:now};const data=JSON.stringify(document);if(input.action==='save'){await env.DB.prepare('INSERT INTO documents(key,draft,published,updated,editor) VALUES(?,?,?,?,?) ON CONFLICT(key) DO UPDATE SET draft=excluded.draft,updated=excluded.updated,editor=excluded.editor').bind(input.key,data,JSON.stringify(source),now,user.userId).run()}else{await env.DB.prepare('INSERT INTO documents(key,draft,published,updated,editor) VALUES(?,?,?,?,?) ON CONFLICT(key) DO UPDATE SET draft=excluded.draft,published=excluded.published,updated=excluded.updated,editor=excluded.editor').bind(input.key,data,data,now,user.userId).run()}return Response.json({ok:true,updated:now})}catch{return fail('Kayıt işlemi başarısız',500)}}
